#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : OpenCASCADE
Version  : 0.18.3
Release  : 1
URL      : https://github.com/tpaviot/oce/archive/OCE-0.18.3.tar.gz
Source0  : https://github.com/tpaviot/oce/archive/OCE-0.18.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.1
Requires: OpenCASCADE-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : cmake
BuildRequires : freetype-dev
BuildRequires : glibc-dev
BuildRequires : glu-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : mesa-dev
BuildRequires : python3
BuildRequires : tcl-dev tk-dev

%description
This is the OCE unittest framework.
In order to run tests, you have to compile GoogleTest from the source code
available in the folder oce/test/gtest-1.6.0

%package license
Summary: license components for the OpenCASCADE package.
Group: Default

%description license
license components for the OpenCASCADE package.


%prep
%setup -q -n oce-OCE-0.18.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543850356
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export SOURCE_DATE_EPOCH=1543850356
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/OpenCASCADE
cp LICENSE_LGPL_21.txt %{buildroot}/usr/share/package-licenses/OpenCASCADE/LICENSE_LGPL_21.txt
cp test/gtest-1.7.0/LICENSE %{buildroot}/usr/share/package-licenses/OpenCASCADE/test_gtest-1.7.0_LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/OpenCASCADE/LICENSE_LGPL_21.txt
/usr/share/package-licenses/OpenCASCADE/test_gtest-1.7.0_LICENSE
